### ISSUE TITLE
A typo with use_gpu ?

### ISSUE THREAD

**Issue by yanyuechuixue** [Photon-AI-Research/NeuralSolvers#66]
https://github.com/Photon-AI-Research/NeuralSolvers/blob/ef7c998d102c7b0e32bfdde73d44a60b68555bd6/PINNFramework/models/moe_finger.py#L170

**Comment by StillerPatrick** [comment]
You are Right. Can you Fix and test it. Looking forward to your PR 👌

**Comment by yanyuechuixue** [comment]
> 

Sorry but I am a very beginner in this field. So it might take a long time for me..

**Comment by StillerPatrick** [comment]
@Jeyhun1 maybe you can help here as the maintainer.
I think you just remove the .cuda line for non gpu execution

**Comment by Jeyhun1** [comment]
Sure. I will fix and test it in a few days
